outdir: '/mnt/local/data'
manifest: '/home/ubuntu/icgc-data/data_listings/donor_manifest_reduced.tsv'
donor_table: '/home/ubuntu/icgc-data/data_listings/donor_table.tsv'
sample_names: '/home/ubuntu/icgc-data/data_listings/sample_names.txt'
genes_bed: '/home/ubuntu/icgc-data/data_listings/genes_hg19.bed'
regions_8p16q: '/home/ubuntu/icgc-data/data_listings/8p16q_regions.bed'
partition: 0
